language: python
python:
  - "2.7.9"
sudo: false
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install git+https://github.com/zefciu/django-search-forms.git@develop
    - pip install git+https://github.com/quamilek/bob-ajax-selects.git@develop
    - pip install git+https://github.com/allegro/django-bob.git@develop
    - pip install coveralls --download-cache $HOME/.pip-cache
    - pip install . --use-mirrors --download-cache $HOME/.pip-cache
    - pip install git+https://github.com/allegro/ralph@develop  --use-mirrors --allow-all-external --allow-unverified ipaddr --allow-unverified postmarkup --allow-unverified python-graph-core --allow-unverified pysphere --download-cache $HOME/.pip-cache
before_install:
    - pip install flake8 --use-mirrors --download-cache $HOME/.pip-cache
    - make flake
script:
  make test-with-coveralls
after_success:
  - coveralls
